---
- name: Install basic utility packages
  apt:
    name:
      - apt-transport-https
      - bc
      - build-essential
      - ca-certificates
      - cmake
      - cups
      - curl
      - fish
      - g++
      - git
      - git-crypt
      - google-chrome-stable
      - gnupg2
      - jq
      - make
      - net-tools
      - nodejs
      - npm
      - openssh-server
      - openvpn
      - pandoc
      - resolvconf
      - snapd
      - thunderbird
      - tmux
      - vim
      - wget
    state: present
    autoclean: true

- name: Install Python-related packages
  apt:
    name:
      - ipython3
      - python3-pip
    state: present
    autoclean: true

- name: Install LaTeX-related packages
  apt:
    name:
      - texlive
      - texlive-latex-extra
      - texlive-publishers
    state: present
    autoclean: true

- name: Install cloud-related packages
  apt:
    name:
      - google-cloud-sdk
      - kubectl
    state: present
    autoclean: true

- name: Install container-related packages
  apt:
    name:
      - docker.io
      - docker-compose
    state: present
    autoclean: true

- name: Install Univa-related packages
  apt:
    name:
      - maven
    state: present
    autoclean: true

- name: Install other packages
  apt:
    name:
      - asciinema
      - gimp
      - gnome-tweak-tool
      - grip
      - kazam
      - kdenlive
      - lutris
      - rhythmbox
    state: present
    autoclean: true

- name: Install zoom from a .deb
  apt:
    deb: https://zoom.us/client/latest/zoom_amd64.deb

- name: Install slack via snap
  snap:
    name: slack
    classic: yes
